---
# Name your file secrets.yml

development:
<<<<<<< HEAD
  REPOSTORE_PATH: repostore
  API_HOST: API_HOST
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku

=======
  DB_FILENAME: db/local/dev.db
  API_KEY: create_google_apikey
  OPENAI_KEY: create_openai_apikey
  REPOSTORE_PATH: repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
>>>>>>> e20a9db (update main)
  # Application
  SESSION_SECRET: <some secret>

test:
<<<<<<< HEAD
  REPOSTORE_PATH: repostore
  API_HOST: API_HOST
=======
  DB_FILENAME: db/local/test.db
  API_KEY:  create_google_apikey
  OPENAI_KEY: create_openai_apikey
  REPOSTORE_PATH: repostore
>>>>>>> e20a9db (update main)
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  # Application
  SESSION_SECRET: <some secret>

production:
<<<<<<< HEAD
  REPOSTORE_PATH: repostore
  API_HOST: API_HOST
=======
  API_KEY:  create_google_apikey
  OPENAI_KEY: create_openai_apikey
  REPOSTORE_PATH: repostore
  API_HOST: 
>>>>>>> e20a9db (update main)
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  # Application
  SESSION_SECRET: <some secret>