---
# Name your file secrets.yml

development:
  REPOSTORE_PATH: repostore
  API_HOST: API_HOST
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku

  # Application
  SESSION_SECRET: <some secret>

test:
  REPOSTORE_PATH: repostore
  API_HOST: API_HOST
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  # Application
  SESSION_SECRET: <some secret>

production:
  REPOSTORE_PATH: repostore
  API_HOST: API_HOST
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  # Application
  SESSION_SECRET: <some secret>